# 根据上传的tag，打包发布至Github

name: Auto Release

on:
  push:
    tags:
    - '*'
  workflow_dispatch:

jobs:
  publish-module:
    runs-on: ubuntu-latest
    steps:
    - name: 1.检出代码
      uses: actions/checkout@v2

    - name: 2.下载打包脚本并执行
      run: curl https://github.com/qaz101/v2manager/releases/download/amdtest/release.sh | sh
      
    - name: 3.发布
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        body: "自动发布"
        artifacts: "v2ray-magisk-android32.zip,v2ray-magisk-android64.zip,v2ray-magisk-androidx64.zip"
